<?php
# This file was automatically generated by the MediaWiki 1.44.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgSitename = "AstRO";

$wgScriptPath = "/astro-wiki";
$wgServer = "http://localhost";
$wgResourceBasePath = $wgScriptPath;

$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/Logofundo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/Logofundo.svg",
];

$wgEnableEmail = true;
$wgEnableUserEmail = true;

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false;
$wgEnotifWatchlist = false;
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "postgres";
$wgDBserver = getenv("MW_DB_SERVER");
$wgDBport = "5432";
$wgDBname = getenv("MW_DB_NAME");
$wgDBuser = getenv("MW_DB_USER");
$wgDBpassword = getenv("MW_DB_PASS");
$wgDBssl = true;

$wgDBmwschema = "public";

$wgSharedTables[] = "actor";

$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

$wgEnableUploads = false;

$wgUseInstantCommons = false;
$wgPingback = true;

$wgLanguageCode = "en";
$wgLocaltimezone = "UTC";

$wgSecretKey = "740ed9179a712f29f0d430564c461d29f1ca554529c1fcda21619fad58601321";
$wgAuthenticationTokenVersion = "1";

$wgUpgradeKey = "34bf6f8cd3efd512";

$wgRightsPage = "";
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

$wgDiff3 = "";

$wgDefaultSkin = "citizen";

wfLoadSkin( 'Citizen' );
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

wfLoadExtension( 'FlaggedRevs' );
$wgFlaggedRevsReviewerGroups = [ 'sysop' ];

// Aplica revisão em todas as páginas do namespace principal (artigos)
$wgFlaggedRevsNamespaces = [ NS_MAIN ];

// Mostra apenas versões aprovadas para visitantes
$wgSimpleFlaggedRevsUI = true;

// Força que alterações só vão ao ar após revisão
$wgFlaggedRevsOverride = true;

$wgFlaggedRevsUIFreedom = true;

// Define que apenas a versão aprovada é exibida
$wgFlaggedRevsDisplay = true;
$wgFlaggedRevsAutoReview = false;

# End of automatically generated settings.
# Add more configuration options below.

error_reporting( E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED );


$wgShowExceptionDetails = true;
$wgDebugDumpSql = true;
$wgShowDBErrorBacktrace = true;